# Your presentation title
title: Bias in AI Systems

# Your presentation description (optional)
description: DATA2080 Bias in AI class on April 2, 2020

# Your name (optional)
author: Sarah Brown
authorurl: sarahmbrown.org

# overall theme
plugins:
  - jekyll-remote-theme

remote_theme: brownsarahm/jekyll-reveal-deck-pack

# The Reveal theme
reveal_theme: black.css

collections:
  slides:
    defaults:

# The Reveal transition
reveal_transition: none

# Path to the used theme (defaults to the Reveal.js standard theme path)
reveal_theme_path: reveal.js/css/theme/

# Additional custom CSS paths
extra_css:

# Custom CSS for highlighting (defaults to reveal.js/lib/css/zenburn.css)
highlight_style_sheet:

# Embed Server-side speaker notes?
reveal_notes_server: false

# Additional reveal.js options
reveal_options:

# Additional reveal.js dependencies
reveal_dependencies:

# Reveal.js subdirectory
reveal_path: reveal.js/

# Exclude directories and/or files from the conversion
exclude:
  - Gemfile*
  - README.md

# Don't change anything below
markdown: kramdown
highlighter: rouge
